# Generated by Django 3.1.5 on 2021-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='adv_category',
            field=models.TextField(blank=True),
        ),
    ]
