# Generated by Django 3.1.5 on 2021-05-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitesubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sitesubscription',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitesubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.DeleteModel(
            name='SiteSubscription',
        ),
    ]
