# Generated by Django 3.1.5 on 2021-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('summary', models.CharField(blank=True, max_length=3000)),
                ('keywords', models.CharField(blank=True, max_length=3000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
