# Generated by Django 3.1.5 on 2021-04-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_notinterested_relatedarticle_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='database.article'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='similar_headline',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='recommend',
            name='similarity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
