# Generated by Django 3.1.5 on 2021-01-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'ArticleCategory',
            },
        ),
        migrations.CreateModel(
            name='UserArticleCategory',
            fields=[
                ('user_article_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.articlecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'UserArticleCategory',
            },
        ),
    ]
