# Generated by Django 3.1.5 on 2021-04-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210404_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'NewsSite',
            },
        ),
        migrations.CreateModel(
            name='SiteSubscription',
            fields=[
                ('site_subscription_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.newssite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'SiteSubscription',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
