# Generated by Django 3.1.5 on 2021-01-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210127_1110'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together={('email',)},
        ),
    ]
