# Generated by Django 3.1.5 on 2021-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
