# Generated by Django 3.1.5 on 2021-02-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_readinghistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'article')},
        ),
    ]
