# Generated by Django 3.1.5 on 2021-02-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20210208_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='readinghistory',
            old_name='id',
            new_name='history_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='id',
            new_name='subscription_id',
        ),
    ]
