# Generated by Django 3.1.5 on 2021-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20210208_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
