# Generated by Django 3.1.5 on 2021-02-09 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20210208_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
