# Generated by Django 3.1.5 on 2021-02-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_readinghistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinghistory',
            old_name='date',
            new_name='history_date',
        ),
    ]
