# Generated by Django 3.1.5 on 2021-02-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20210209_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'Recommend',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'Bookmark',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
