# Generated by Django 3.1.5 on 2021-02-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_bookmark_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='bookmark_id',
            new_name='recommend_id',
        ),
    ]
