# Generated by Django 3.1.5 on 2021-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20210218_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
